orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tatchumnono/example_ci
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  publishLatestToHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo “$DOCKERHUB_PASS” | docker login -u “$DOCKERHUB_USERNAME” -p “$DOCKERHUB_PASSWORD” --password-stdin
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - publishLatestToHub
